### ISSUE TITLE
Provide valuable type information

### ISSUE THREAD

**Issue by awaltert** [zalando-incubator/lib-oauth-tooling#41]
Type definitions serve multiple purposes. One one side, they help the compiler to determine choices depending of context and enrich the development workflow.   
On the other side, do they provide documentation for possible consumers and readers.

In terms of  #15 and #30, I would like to suggest to enrich the project with valuable type information to promote the usage of this library.

**Comment by bzums** [comment]
@awaltert @Retro64 wrt https://github.com/zalando-incubator/lib-oauth-tooling/commit/541d9cd411a4850dcd4c0cecd7af2f38f5069ca9: regarding the interface definitions of `Token` and `TokenInfo` we have to keep in mind that we want to get independent of the oAuth2 server implementation (currently we are "bound" to Zalandos implementation). So we have to find out which properties are mandatory for an oAuth2 server imolementation. Maybe the RFC is helpful (https://tools.ietf.org/html/rfc6749) however i did no research until now in that direction.

**Comment by Retro64** [comment]
@bzums Refactoring should be easier afterwards, if the types are established. Should be done with #39 or #40
